version: '2'

services:
  bankofmallorca.customer:
    image: bankofmallorca.customer
    build:
      context: ./BankOfMallorca.Customer
      dockerfile: Dockerfile
    links:
      - bankofmallorca.customer.eventstore:eventstore
  bankofmallorca.customer.eventstore:
    image: eventstore/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"